version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - /path/to/host/wordpress:/var/www/html
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - 81:80
    volumes: 
      - /path/to/host/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME:  
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress


